src/SignService/Controllers/AdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SignService.Services;

namespace SignService.Controllers
{
    [Authorize(Roles = "admin_signservice")]
    [RequireHttps]
    public class AdminController : Controller
    {
        readonly IUserAdminService adminService;

        public AdminController(IUserAdminService adminService)
        {
            this.adminService = adminService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RegisterExtensionAttributes()
        {
            await adminService.RegisterExtensionPropertiesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnRegisterExtensionAttributes()
        {
            await adminService.UnRegisterExtensionPropertiesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

src/SignService/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SignService.Models;
using SignService.Services;

namespace SignService.Controllers
{
    [Authorize(Roles = "admin_signservice")]
    [RequireHttps]
    public class UsersController : Controller
    {
        readonly IUserAdminService adminService;
        readonly IKeyVaultAdminService keyVaultAdminService;

        public UsersController(IUserAdminService adminService, IKeyVaultAdminService keyVaultAdminService)
        {
            this.adminService = adminService;
            this.keyVaultAdminService = keyVaultAdminService;
        }
        public async Task<IActionResult> Index()
        {
            var users = await adminService.GetSignServiceUsersAsync();

            return View(users);
        }

        public async Task<IActionResult> Search(string displayName)
        {
            var users = await adminService.GetUsersAsync(displayName);

            return View(users);
        }

        public IActionResult Create()
        {
            return View(new CreateSignServiceUserModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSignServiceUserModel createModel)
        {
            if (createModel.Configured)
            {
                if (string.IsNullOrWhiteSpace(createModel.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(createModel.KeyVaultUrl), $"{nameof(createModel.KeyVaultUrl)} is required when Configured");
                }

                if (string.IsNullOrWhiteSpace(createModel.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(createModel.TimestampUrl), $"{nameof(createModel.TimestampUrl)} is required when Configured");
                }

                if (string.IsNullOrWhiteSpace(createModel.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(createModel.CertificateName), $"{nameof(createModel.CertificateName)} is required when Configured");
                }
            }
            if (!ModelState.IsValid)
            {
                return View(createModel);
            }

            try
            {
                var res = await adminService.CreateUserAsync(createModel.DisplayName,
                                                             createModel.Username,
                                                             createModel.Configured,
                                                             createModel.KeyVaultUrl,
                                                             createModel.CertificateName,
                                                             createModel.TimestampUrl);

                var user = res.Item1;

                // create the associated key vault if the vault isn't set
                if (string.IsNullOrWhiteSpace(user.KeyVaultUrl))
                {
                    var vault = await keyVaultAdminService.CreateVaultForUserAsync(user.ObjectId.Value.ToString(), user.UserPrincipalName, user.DisplayName);

                    // Update the vault attribute
                    await adminService.UpdateUserAsync(user.ObjectId.Value, user.DisplayName, user.SignServiceConfigured, vault.VaultUri, user.KeyVaultCertificateName, user.TimestampUrl);
                    user.KeyVaultUrl = vault.VaultUri;
                }

                ViewBag.Password = res.Item2;

                var model = new UserDetailsModel
                {
                    User = res.Item1
                };

                return View(nameof(Details), model);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(createModel);
            }
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var model = await GetUserDetailsForId(id);

            return View(model);
        }

        async Task<UserDetailsModel> GetUserDetailsForId(Guid id)
        {
            var user = await adminService.GetUserByObjectIdAsync(id);

            // See if we have a key vault
            string vaultName = null;
            if (!string.IsNullOrWhiteSpace(user.KeyVaultUrl))
            {
                var uri = new Uri(user.KeyVaultUrl);
                vaultName = uri.Host.Substring(0, uri.Host.IndexOf("."));
            }
            var model = new UserDetailsModel
            {
                User = user,
                VaultName = vaultName
            };
            return model;
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var user = await adminService.GetUserByObjectIdAsync(id);

            List<CertificateModel> certs = null;
            if (!string.IsNullOrWhiteSpace(user.KeyVaultUrl))
            {
                certs = await keyVaultAdminService.GetCertificatesInVaultAsync(user.KeyVaultUrl);
            }
            if (certs == null)
            {
                certs = new List<CertificateModel>();
            }

            var model = new UpdateCreateSignServiceUserModel
            {
                ObjectId = user.ObjectId.Value,
                Username = user.UserPrincipalName,
                Configured = user.SignServiceConfigured ?? false,
                CertificateName = user.KeyVaultCertificateName,
                DisplayName = user.DisplayName,
                KeyVaultUrl = user.KeyVaultUrl,
                TimestampUrl = user.TimestampUrl,

                // Only show enabled ones here
                CertificatesModels = certs.Where(cm => cm.Attributes?.Enabled == true).ToList()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, UpdateCreateSignServiceUserModel model)
        {
            if (model.Configured)
            {
                if (string.IsNullOrWhiteSpace(model.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(model.KeyVaultUrl), $"{nameof(model.KeyVaultUrl)} is required when Configured");
                }

                if (string.IsNullOrWhiteSpace(model.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(model.TimestampUrl), $"{nameof(model.TimestampUrl)} is required when Configured");
                }

                if (string.IsNullOrWhiteSpace(model.KeyVaultUrl))
                {
                    ModelState.TryAddModelError(nameof(model.CertificateName), $"{nameof(model.CertificateName)} is required when Configured");
                }
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await adminService.UpdateUserAsync(id,
                                                   model.DisplayName?.Trim(),
                                                   model.Configured,
                                                   model.KeyVaultUrl?.Trim(),
                                                   model.CertificateName?.Trim(),
                                                   model.TimestampUrl?.Trim());

                return RedirectToAction(nameof(Details), new { id });
            }
            catch (Exception e)
            {
                ModelState.TryAddModelError("", e.Message);
                return View(model);
            }
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var user = await adminService.GetUserByObjectIdAsync(id);

            var model = new UpdateCreateSignServiceUserModel
            {
                ObjectId = user.ObjectId.Value,
                Username = user.UserPrincipalName,
                Configured = user.SignServiceConfigured ?? false,
                CertificateName = user.KeyVaultCertificateName,
                DisplayName = user.DisplayName,
                KeyVaultUrl = user.KeyVaultUrl,
                TimestampUrl = user.TimestampUrl
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id, UpdateCreateSignServiceUserModel model)
        {
            var user = await adminService.GetUserByObjectIdAsync(id);

            // Soft delete, just clear out the sign service attributes
            try
            {
                await adminService.UpdateUserAsync(id,
                                                   user.DisplayName,
                                                   null,
                                                   null,
                                                   null,
                                                   null);
            }
            catch (Exception)
            {
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ResetPassword(Guid id)
        {
            var user = await adminService.GetUserByObjectIdAsync(id);


            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(Guid id, GraphUser model)
        {
            try
            {
                var details = await GetUserDetailsForId(id);

                var pw = await adminService.UpdatePasswordAsync(id);

                ViewBag.Password = pw;


                return View(nameof(Details), details);
            }
            catch (Exception e)
            {
                ModelState.TryAddModelError("", e.Message);
                return View(model);
            }
        }
    }
}

src/SignService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SignService</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SignService</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (@User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="KeyVault" asp-action="Index">Key Vaults</a></li>

                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Adv Setup</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016-2018 - Oren Novotny. <span>Build: @Program.AssemblyInformationalVersion</span></p> 
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>