src/SignService/Controllers/KeyVaultController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SignService.Models;
using SignService.Services;
using SignService.Utils;

namespace SignService.Controllers
{
    public class KeyVaultController : Controller
    {
        readonly IKeyVaultAdminService keyVaultAdminService;

        public KeyVaultController(IKeyVaultAdminService keyVaultAdminService)
        {
            this.keyVaultAdminService = keyVaultAdminService;
        }
        // GET: KeyVault
        public async Task<IActionResult> Index()
        {
            var vaults = await keyVaultAdminService.ListKeyVaultsAsync();

            return View(vaults);
        }

        // GET: KeyVault/Details/5
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var vault = await keyVaultAdminService.GetVaultAsync(id);
                var certificates = await keyVaultAdminService.GetCertificatesInVaultAsync(vault.VaultUri);

                // See if there are any pending ops
                var ops = certificates.Select(c => new { cert = c, operation = keyVaultAdminService.GetCertificateOperation(vault.VaultUri, c.Name) }).ToList();
                await Task.WhenAll(ops.Select(a => a.operation));

                foreach (var op in ops)
                {
                    op.cert.Operation = op.operation.Result; // completed, safe
                }

                var model = new KeyVaultDetailsModel
                {
                    Vault = vault,
                    CertificateModels = ops.Select(a => a.cert).ToList()
                };

                return View(model);
            }
            catch (Exception)
            {
                ViewBag.Id = id;
                return View("Details.Error");
            }
        }

        // GET: KeyVault/CreateCertificate/vaultName
        public IActionResult CreateCertificate(string id)
        {
            return View(new CreateCertificateRequestModel { VaultName = id });
        }

        // POST: KeyVault/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCertificate(CreateCertificateRequestModel model)
        {
            try
            {
                var csr = await keyVaultAdminService.CreateCsrAsync(model.VaultName, model.CertificateName, model.CertificateName);

                return RedirectToAction(nameof(Details), new { id = model.VaultName });
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(model);
            }
        }

        public async Task<IActionResult> CertificateRequest(string id, string certificateName)
        {
            var vault = await keyVaultAdminService.GetVaultAsync(id);
            var op = await keyVaultAdminService.GetCertificateOperation(vault.VaultUri, certificateName);

            string str = null;
            if (op.Csr?.Length > 0)
            {
                str = Crypt32.CryptBinaryToString(op.Csr, true, true);
            }
            var model = new UpdateCertificateRequestModel
            {
                CertificateName = certificateName,
                VaultName = id,
                Csr = str
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MergeCertificate(UpdateCertificateRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(CertificateRequest), model);
            }

            byte[] data;
            using (var ms = new MemoryStream())
            {
                // get file data
                await model.Certificate.CopyToAsync(ms);
                ms.Position = 0;
                data = ms.ToArray();
            }

            try
            {
                await keyVaultAdminService.MergeCertificate(model.VaultName, model.CertificateName, data);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(nameof(CertificateRequest), model);
            }

            return RedirectToAction(nameof(Details), new { id = model.VaultName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelCertificateRequest(UpdateCertificateRequestModel model)
        {
            var op = await keyVaultAdminService.CancelCsrAsync(model.VaultName, model.CertificateName);

            return RedirectToAction(nameof(Details), new { id = model.VaultName });
        }
    }
}

src/SignService/Views/KeyVault/CertificateRequest.cshtml
@model SignService.Models.UpdateCertificateRequestModel

@{
    ViewData["Title"] = "Create Certificate Request";
}

<h2>View Certificate Request</h2>

<h4>View Certificate Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <div>
<textarea cols="100" rows="20" readonly="readonly">
@Model.Csr
</textarea>
        </div>

        <form asp-action="MergeCertificate" asp-antiforgery="true" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Certificate" class="control-label"></label>
                <input asp-for="Certificate" class="form-control" />
                <span asp-validation-for="Certificate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Upload CA Cer" class="btn btn-default"/>
            </div>
            <input asp-for="VaultName" class="hidden"/>
            <input asp-for="CertificateName" class="hidden"/>
            <input asp-for="Csr" class="hidden"/>
        </form>
        <form asp-action="CancelCertificateRequest" asp-antiforgery="true" >
            <input asp-for="VaultName" class="hidden"/>
            <input asp-for="CertificateName" class="hidden"/>
            <div class="form-group">
                <input type="submit" value="Cancel Request" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to Vault Details", "Details", "KeyVault", new { id = Model.VaultName })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SignService/Views/KeyVault/CreateCertificate.cshtml
@model SignService.Models.CreateCertificateRequestModel

@{
    ViewData["Title"] = "Create Certificate Request";
}

<h2>Create Certificate Request</h2>

<h4>Create Certificate Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCertificate" asp-antiforgery="true">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CertificateName" class="control-label"></label>
                <input asp-for="CertificateName" class="form-control" />
                <span asp-validation-for="CertificateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
            <input asp-for="VaultName" class="hidden" />
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to Vault Details", "Details", "KeyVault", new { id = Model.VaultName })
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SignService/Views/KeyVault/Details.Error.cshtml
@model SignService.Models.KeyVaultDetailsModel

@{
    ViewData["Title"] = "Key Vault Details";
}

<h2>Error: Vault @ViewBag.Id is not in the correct resource group. Cannot view details here.</h2>


<div>
    <a asp-action="Index">Back to List</a>
</div>

src/SignService/Views/KeyVault/Details.cshtml
@model SignService.Models.KeyVaultDetailsModel

@{
    ViewData["Title"] = "Key Vault Details";
}

<h2>Vault Details for @Model.Vault.DisplayName (@Model.Vault.Username)</h2>

<h4>Details</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vault.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vault.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vault.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vault.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vault.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vault.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vault.VaultUri)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vault.VaultUri)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vault.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vault.Location)
        </dd>
    </dl>
</div>
<h4>Certificates</h4>
<hr />
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Thumbprint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Attributes.NotBefore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Attributes.Expires)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Attributes.Enabled)
        
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Attributes.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CertificateModels[0].Operation.Status)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.CertificateModels) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Thumbprint)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attributes.NotBefore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attributes.Expires)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attributes.Enabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attributes.Updated)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Operation.Status)
            </th>
            <th>
                @if (item.Operation?.Status == "inProgress")
                {
                    @Html.ActionLink("View", "CertificateRequest", new
                    {
                        id = Model.Vault.Name,
                        certificateName = item.Name
                    });
                }
                
            </th>
        </tr>
    }
    </tbody>
</table>

<div>
    @Html.ActionLink("New Certificate", "CreateCertificate", new {  id = Model.Vault.Name }) |
    <a asp-action="Index">Back to List</a>
</div>

src/SignService/Views/KeyVault/Index.cshtml
@model IEnumerable<SignService.Models.VaultModel>

@{
    ViewData["Title"] = "Key Vaults";
}

<h2>Key Vaults</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DisplayName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VaultUri)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VaultUri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Name }) 
            </td>
        </tr>
}
    </tbody>
</table>